name: ut2
options:
  bundleIdPrefix: com.ut2
settings:
  base:
    SWIFT_VERSION: 5.0
targets:
  ut2:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - UT2
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ut2.game
        GENERATE_INFOPLIST_FILE: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        CODE_SIGN_STYLE: Automatic
    dependencies:
      - sdk: SpriteKit.framework
      - sdk: SwiftUI.framework
